 /******************************************************
 * PLEASE DO NOT EDIT THIS FILE
 * the verification process may break
 * ***************************************************/

'use strict';

var fs = require('fs');
var express = require('express');
var app = express();
var multer  = require('multer')
var upload = multer()

app.use('/public', express.static(process.cwd() + '/public'));
  
app.route('/')
    .get(function(req, res) {
		  res.sendFile(process.cwd() + '/views/index.html');
    })

app.post('/fileupload', upload.any(), function(req, res) {
      res.json({"size": req.files[0].size})
    })


// Respond not found to all the wrong routes
app.use(function(req, res){
  res.status(404);
  res.type('txt').send('Not found');
});


app.listen(process.env.PORT, function () {
  console.log('Node.js listening ...');
});

